services:
  cibot:
    image: mrexz/cibot:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"